config/routes.rb
Rails.application.routes.draw do

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  root :to => 'pages#home'
  get '/home' => 'pages#home'
  get '/home/food' => 'pages#food'
  get '/home/animal' => 'pages#animal'
  get 'home/travel' => 'pages#travel'
  get 'home/decor'=> 'pages#decor'
  get 'home/plant' => 'pages#plant'
  get 'home/other' => 'pages#other'

  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :posts, :only => [:new, :show, :create, :edit, :update, :index, :destroy]

  resources :posts do
    resources :comments
  end

  post ':user_id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :text
#  email           :text
#  profile         :text
#  header          :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#  admin           :boolean          default(FALSE)
#  picture         :string
#

class User < ApplicationRecord

  has_secure_password
  has_many :posts, dependent: :destroy

  validates :email, :presence => true, :uniqueness => true
  validates :name, :presence => true

  has_many :comments, dependent: :destroy

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  # follow / unfollow methods
  # has_many :follow_user
  # has_many :unfollow_user

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, :only => [:edit]

  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end

  end

  def edit
    @user = User.find params[:id]
  end

  def update

    user = @current_user

    cloudinary1 = Cloudinary::Uploader.upload( params[ "user" ][ "profile" ] )
    cloudinary2 = Cloudinary::Uploader.upload( params[ "user" ][ "header" ] )
    params["user"]["profile"] = cloudinary1['url']
    params["user"]["header"] = cloudinary2['url']


    user.update user_params
    redirect_to user_path
  end


  def follow(user_id)
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :header)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def current_user_is_following(current_user_id, followed_user_id)
  relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
  return true if relationship
  end

end

app/views/users/edit.html.erb
<nav class="edit-nav">
    <div class="profile-links">

        <% if @current_user.present? %>
            <div class="user-links">
                <%= link_to 'home', root_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            |
            <% else %>
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                <% end %>

    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>Update details</h1>

<%= form_for @user, :html => { :multipart => true}, :class => "form-horizontal" do |f| %>
    <br>

    <div class="form-group" style="margin: 0 auto; max-width: 400px">
        <%= f.label :email %>
            <%= f.email_field :email, :class => "form-control" %>
                <br>
                <div class="form-group" style="margin: 0 auto; max-width: 400px">
                    <%= f.label :profile %>
                        <%= f.file_field :profile, :class => "form-control" %>
                            <br>
                            <div class="form-group" style="margin: 0 auto; max-width: 400px">
                                <%= f.label :header %>
                                    <%= f.file_field :header, :class => "form-control" %>
                                        <br>
                                        <label></label>
                                        <div class="button" style="text-align: center">
                                            <%= f.submit "update me!", :class => "btn btn-info" %>
                                                <% end %>

app/views/users/index.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to "other posts", posts_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to 'home', root_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                <% end %>
                    |
    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>others you may like to follow..</h1>

<div class="row">
    <% @users.each do |user| %>
        <% next if user.id == @current_user.id %>

            <div class="col-xs-6 col-md-4">
                <div class="polaroid" style="width: 25vw; padding: 5px; margin: 0 auto">
                    <% if user.profile.nil? %>
                        <p>
                            <%= link_to user.name, user_path(user.id) %>
                        </p>
                        <%= image_tag 'default-profile.jpg', :class => "img-responsive"%>
                      <% else %>
                          <p>
                            <%= link_to user.name, user_path(user.id) %>
                          </p>
                        <%= image_tag user.profile, :class => "img-responsive" %>
                      <% end %>
                </div>
            </div>

            <% end %>
</div>

app/views/users/new.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to "other posts", posts_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'home', root_path %>
                </div>
                <% end %>
                    
    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>
<h1>Sign Up</h1>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
    </ol>
    <% end %>

        <%= form_for @user, :class => "form-horizontal" do |f| %>
            <div class="form-group" style="margin: 0 auto; max-width: 400px">
                <%= f.label :name %>
                    <%= f.text_field :name, :class => "form-control" %>
            </div>

            <div class="form-group" style="margin: 0 auto; max-width: 400px">
                <%= f.label :email %>
                    <%= f.email_field :email, :class => "form-control" %>
            </div>

            <div class="form-group" style="margin: 0 auto; max-width: 400px">
                <%= f.label :password %>
                    <%= f.password_field :password, :class => "form-control" %>
            </div>

            <div class="form-group" style="margin: 0 auto; max-width: 400px">
                <%= f.label :password_confirmation %>
                    <%= f.password_field :password_confirmation, :class => "form-control" %>
            </div>

            <label></label>
            <div class="button" style="text-align: center">
                <%= f.submit "sign me up!", :class => "btn btn-info" %>
                    <% end %>

app/views/users/show.html.erb
<nav>
  <div class="profile-links">
    <% if @current_user.present? %>
      <div class="user-links">
        <%= link_to "edit profile", edit_user_path(@current_user) %>
      </div>
        |
      <div class="user-links">
        <%= link_to "other users", users_path %>
      </div>
        |
      <div class="user-links">
        <%= link_to "new post", new_post_path %>
      </div>
        |
      <div class="user-links">
        <%= link_to "other posts", posts_path %>
      </div>
        |
      <div class="user-links">
        <%= link_to 'home', root_path %>
      </div>
        |
      <div class="user-links">
        <%= link_to "profile", user_path(@current_user.id) %>
      </div>
        |
      <div class="user-links">
        <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
      </div>
    <% else %>
      <div class="user-links">
        <%= link_to 'sign up', new_user_path %>
      </div>
        |
      <div class="user-links">
        <%= link_to 'login', login_path %>
      </div>
    <% end %>
        |
  </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<% if @user.header.nil? %>
    <div class="banner" style="width: 100vw; height: 80vh; background-size: cover; margin: 0 auto;
     background-image: url(<%= asset_path 'default-header.jpg' %>)">
<% else %>
    <div class="banner" style="width: 100vw; height: 80vh; background-size: cover; margin: 0 auto;
     background-image: url(<%= @user.header %>)">
<% end %>
    </div>

  <div>
    <% if @user.profile.nil? %>
      <%= image_tag 'default-profile.jpg', :class => "profile-pic" %>
    <% else %>
      <%= image_tag @user.profile, :class => "profile-pic" %>
    <% end %>
  </div>

  <div class="welcome">
    <% if @current_user.present? && @user.id == @current_user.id %>
      welcome <%= @user.name %>
  <div>
    <% else %>
      <%= @user.name %>
    <% end %>
  </div>

<div class="parent">
  <div class="pic">
    <div class="row-user">
      <% @user.posts.each do |post| %>
        <% next if post.user_id.nil? %>
          <div class="col-xs-6 col-md-4">
            <div class="polaroid" style="width: 25vw; padding: 5px; margin: 0 auto">
              <% if post.photograph.nil? %>
                <%= image_tag 'default-post.jpg', :class => "img-responsive" %>
                  <p><%= link_to post.title, post_path(post.id) %></p>
              <% else %>
                  <%= image_tag(post.photograph, :class => "img-responsive") %>
                    <p><%= link_to post.title, post_path(post.id) %></p>
              <% end %>
            </div>
         </div>
      <% end %>
    </div>
  </div>
</div>

<div>
  <% if @user.id != @current_user.id %>
    <% if current_user_is_following(@current_user.id, @user.id) %>
      <%= link_to 'Following', unfollow_user_path(@user.id), remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
    <% else %>
      <%= link_to 'Follow', follow_user_path(@user.id), remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
    <% end %>
  <% end %>
</div>

  <script>
    // Week 7 code below:
    $(document).ready(function() {
    $('.btn.unfollow-button, .btn.follow-button').on('ajax:success', function(response) {
      if ($(this).is('#unfollow-button')) {
        $('#unfollow-button').text('Follow').attr('class', 'btn follow-button')
          .attr('href', "/<%= @user.id %>/follow_user").attr('id', 'follow-button');
      } else {
        $('#follow-button').attr('class', 'btn unfollow-button').text('Following')
          .attr('href', "/<%= @user.id %>/unfollow_user").attr('id', 'unfollow-button');
          }
      });
    })
  </script>