config/routes.rb
Rails.application.routes.draw do

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  root :to => 'pages#home'
  get '/home' => 'pages#home'
  get '/home/food' => 'pages#food'
  get '/home/animal' => 'pages#animal'
  get 'home/travel' => 'pages#travel'
  get 'home/decor'=> 'pages#decor'
  get 'home/plant' => 'pages#plant'
  get 'home/other' => 'pages#other'

  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :posts, :only => [:new, :show, :create, :edit, :update, :index, :destroy]

  resources :posts do
    resources :comments
  end

  post ':user_id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


end

app/views/pages/animal.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>


            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                <div class="user-links">
                    <%= link_to 'home', root_path %>
                </div>
                |
                <% end %>
                
    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>animals</h1>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 120px">
            <p>awwwwww</p>
            <%= image_tag "animals/animal-3.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 80px">
            <p>hello</p>
            <%= image_tag "animals/animal-4.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 20px">
            <p>peek-a-boo</p>
            <%= image_tag "animals/animal-6.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 80px">
            <p>arghhhhhhhhh!</p>
            <%= image_tag "animals/animal-2.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 50px; margin-left: 80px">
            <p>nom nom nom</p>
            <%= image_tag "animals/animal-5.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 80px; margin-right: 120px">
            <p>eeeeeekkkkkkk</p>
            <%= image_tag "animals/animal-1.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

app/views/pages/animals.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<nav>
<div class="profile-links">
  <% if @current_user.present? %>

    <div class="user-links" >
      <%= link_to 'home', root_path %>
    </div>
       |
    <div class="user-links" >
      <%= link_to "profile", user_path(@current_user.id) %>
    </div>
        |
    <div class="user-links" >
      <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
    </div>
     <% else %>
    <div class="user-links" >
       <%= link_to 'sign up', new_user_path %>
    </div>
        |
    <div class="user-links" >
       <%= link_to 'login', login_path %>
    </div>
     <% end %>
     |
  </div>
   <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


    <h1>animals</h1>

<div class="row">

  <div class="col-xs-6 col-md-4">
      <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 20px">
        <p>food</p>
        <%= image_tag "animals/animal-3.jpg", :class => "img-responsive", :alt => "Responsive image" %>
      </div>
  </div>

  <div class="col-xs-6 col-md-4">
      <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 0px">
        <p>travel</p>
        <%= image_tag "animals/animal-4.jpg", :class => "img-responsive", :alt => "Responsive image" %>
      </div>
  </div>

  <div class="col-xs-6 col-md-4">
      <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 20px">
        <p>animals</p>
        <%= image_tag "animals/animal-6.jpg", :class => "img-responsive", :alt => "Responsive image" %>
      </div>
  </div>

</div>

<div class="row">

  <div class="col-xs-6 col-md-4">
      <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 20px">
        <p>home decor</p>
        <%= image_tag "animals/animal-2.jpg", :class => "img-responsive", :alt => "Responsive image" %>
      </div>
  </div>

  <div class="col-xs-6 col-md-4">
      <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 40px">
        <p>plants</p>
        <%= image_tag "animals/animal-1.jpg", :class => "img-responsive", :alt => "Responsive image" %>
      </div>
  </div>

  <div class="col-xs-6 col-md-4">
      <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 20px">
        <p>other</p>
        <%= image_tag "animals/animal-5.jpg", :class => "img-responsive", :alt => "Responsive image" %>
      </div>
  </div>

</div>

app/views/pages/decor.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                <div class="user-links">
                    <%= link_to 'home', root_path %>
                </div>
                |
                <% end %>
                
    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>home decor</h1>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 60px">
            <p></p>
            <%= image_tag "decor/decor-4.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 40px">
            <p></p>
            <%= image_tag "decor/decor-1.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 70px">
            <p></p>
            <%= image_tag "decor/decor-2.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 80px; margin-top: 50px">
            <p></p>
            <%= image_tag "decor/decor-5.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 50px; margin-left: 20px">
            <p></p>
            <%= image_tag "decor/decor-3.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 50px; margin-right: 80px">
            <p></p>
            <%= image_tag "decor/decor-6.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

app/views/pages/food.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'home', root_path %>
                </div>
                |
                <% end %>
                    
    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>food</h1>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 50px; margin-left: 40px">
            <p>whoa!</p>
            <%= image_tag "food/food-1.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 0px">
            <p>yum!</p>
            <%= image_tag "food/food-3.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 40px; margin-right: 40px">
            <p>delicious</p>
            <%= image_tag "food/food-5.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 100px; margin-left: 40px">
            <p>cheeky</p>
            <%= image_tag "food/food-2.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 40px">
            <p>that looks great</p>
            <%= image_tag "food/food-4.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 80px; margin-right: 40px">
            <p>indulge!</p>
            <%= image_tag "food/food-6.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

app/views/pages/home.html.erb
<nav class="home-links" style="font-size: 20px; color: black; text-align: right; padding: 0 20px;
     padding: 0 20px; font-family: 'Kalam', cursive">
    <%= link_to 'home', root_path %>
        </div>
        |
        <% if @current_user.present? %>
            <div class="main-links" style="font-size: 20px; color: #04f2da; display: inline-block;
       padding: 0 20px; font-family: 'Kalam', cursive">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="main-links" style="font-size: 20px; color: #04f2da; display: inline-block;
      padding: 0 20px; font-family: 'Kalam', cursive">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="main-links" style="font-size: 20px; color: #04f2da; display: inline-block;
      padding: 0 20px; font-family: 'Kalam', cursive">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="main-links" style="font-size: 20px; color: #04f2da; display: inline-block;
          padding: 0 20px; font-family: 'Kalam', cursive">
                    <%= link_to 'login', login_path, :class => "links" %>
                </div>
                <% end %>
                    |
                    <%= image_tag "home/logo.png", :class => "logo"%>
</nav>


<h1>heimat</h1>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 40px;">
            <p>food</p>
            <%= link_to image_tag("food/food-home.jpg", :class => "img-responsive",
            :alt => "some bright coloured fruits, not quite food but i like the simple artistic colours"), home_food_path %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 30px">
            <p>travel</p>
            <%= link_to image_tag("travel/travel-home.jpg", :class => "img-responsive",
            :alt => "breathtaking view of the ocean, great holiday destination"), home_travel_path %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 90px;">
            <p>animals</p>
            <%= link_to image_tag("animals/animals-home.jpg", :class => "img-responsive",
            :alt => "cute mini piglet i named bacon"), home_animal_path %>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 30px">
            <p>home decor</p>
            <%= link_to image_tag("decor/decor-home.jpg", :class => "img-responsive",
            :alt => "some simple home decor from kmart"), home_decor_path %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 40px">
            <p>plants</p>
            <%= link_to image_tag("plants/plant-home.jpg", :class => "img-responsive",
            :alt => "a beautiful lavender field to roll around in but might have too many bees"), home_plant_path %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 30px">
            <p>other</p>
            <%= link_to image_tag("everything/other-home.jpg", :class => "img-responsive",
            :alt => "an artistic black and white photo of a flower, i think lotus"), home_other_path %>
        </div>
    </div>

</div>
<br>
<br>

<h4>Heimat is German for the place we're connected to that shaped who we are. <br> Most of us associate who we are with where we come from. <br> The food, the music, the art, friends, family, school, childhood memories and adulthood experiences, <br> all stem from the place we call home. <br> Heimat refers to the place that makes us who we are. <br> It refers to the attitudes and beliefs we’ve formed that have evolved over generations. <br> It doesn’t refer to just homeland pride, but our roots.<br>
</h4>

app/views/pages/other.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to 'home', root_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                |
                <% end %>

    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>other..</h1>

app/views/pages/plant.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'home', root_path %>
                </div>
                |
                <% end %>

    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>plants</h1>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 60px; margin-top: 60px">
            <p>autumn time</p>
            <%= image_tag "plants/plant-1.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 40px">
            <p>pretty</p>
            <%= image_tag "plants/plant-6.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 70px; margin-top: 50px">
            <p>peaceful tree</p>
            <%= image_tag "plants/plant-2.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 80px; margin-top: 50px">
            <p>i'm growing!</p>
            <%= image_tag "plants/plant-4.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 50px; margin-left: 20px">
            <p>spiral</p>
            <%= image_tag "plants/plant-5.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 50px; margin-right: 80px">
            <p>tulips!</p>
            <%= image_tag "plants/plant-3.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

app/views/pages/travel.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                <div class="user-links">
                    <%= link_to 'home', root_path %>
                </div>
                 |
                <% end %>

    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>travel</h1>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 50px; margin-top: 0px">
            <p>banff</p>
            <%= image_tag "travel/travel-2.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-top: 0px ">
            <p>vietnam</p>
            <%= image_tag "travel/travel-5.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 50px">
            <p>iceland</p>
            <%= image_tag "travel/travel-3.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>

<div class="row">

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 50px">
            <p>whitsundays</p>
            <%= image_tag "travel/travel-4.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-left: 80px">
            <p>japan.. sukura</p>
            <%= image_tag "travel/travel-6.jpg", :class => "img-responsive", :alt => "Responsive image", :size => "250x150" %>
        </div>
    </div>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="transform: rotateZ(<%= rand(-5..5) %>deg); margin-right: 50px">
            <p>colosseum</p>
            <%= image_tag "travel/travel-1.jpg", :class => "img-responsive", :alt => "Responsive image" %>
        </div>
    </div>

</div>