config/routes.rb
Rails.application.routes.draw do

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  root :to => 'pages#home'
  get '/home' => 'pages#home'
  get '/home/food' => 'pages#food'
  get '/home/animal' => 'pages#animal'
  get 'home/travel' => 'pages#travel'
  get 'home/decor'=> 'pages#decor'
  get 'home/plant' => 'pages#plant'
  get 'home/other' => 'pages#other'

  resources :users

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :posts, :only => [:new, :show, :create, :edit, :update, :index, :destroy]

  resources :posts do
    resources :comments
  end

  post ':user_id/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user


end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :text
#  photograph :text
#  caption    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  picture    :string
#  user_id    :integer
#

class Post < ApplicationRecord

  belongs_to :user, :optional => true

  has_many :comments, dependent: :destroy

  attr_accessor :content, :name
  has_many :comments

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :check_if_logged_in, :only => [:posts]
  before_action :own_post, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def show
    @post = Post.find params[:id]
  end

  def create
    cloudinary = Cloudinary::Uploader.upload( params[ "post" ][ "photograph" ] )

    @post = Post.new post_params
    @post.photograph = cloudinary['url']
    
    if @post.save
      @current_user.posts << @post
      redirect_to user_path(@current_user.id)
    else
      flash[:alert] = "Your new post couldn't be created! Please check the form."
      render :new
    end
  end

  def edit
    @post = Post.find params[:id]
  end

  def update
    @post = @current_user.posts
    if @post.update post_params
      redirect_to post_path
    else
      flash.now[:alert] = "Update failed. Please check the form."
      render :edit
    end
  end

  def index
    @posts = Post.all.order(:created_at)
  end

  def destroy
    post = Post.find params[:id]
    post.destroy
    redirect_to user_path(@current_user.id)
  end


  private

  def post_params
    params.require(:post).permit(:title, :photograph, :caption)
  end

  def own_post
    unless @current_user.post_ids.include? params[:id].to_i
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to user_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

    <% if @post.errors.any? %>
        <div id="error_explanation">
            <h3>
                <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
            <ul>
                <% @post.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>

            <fieldset class="field">
                <%= f.label :title %><br>
                    <%= f.text_field :title %>
            </fieldset>

            <fieldset class="field">
                <%= f.label :image %><br>
                    <%= f.file_field :image %>
            </fieldset>

            <fieldset class="field">
                <%= f.label :caption %><br>
                    <%= f.text_area :caption %>
            </fieldset>

            <% end %>

app/views/posts/edit.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>
            <div class="user-links">
                <%= link_to "edit profile", edit_user_path(@current_user) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "new post", new_post_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "other users", users_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "other posts", posts_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to 'home', root_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                <% end %>
                    |
    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>

<h1>Update post</h1>

<% if @post.id == @current_user.id %>

    <%= form_for @post, :class => "form-horizontal" do |f| %>

        <% if @post.errors.any? %>
            <div id="error_explanation">
                <h3>
                    <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
                <ul>
                    <% @post.errors.full_messages.each do |message| %>
                        <li>
                            <%= message %>
                        </li>
                        <% end %>
                </ul>
            </div>
            <% end %>

                <div class="form-group" style="margin: 0 auto; max-width: 400px">
                    <%= f.label :title %> <br>
                        <%= f.text_field :title, :class => "form-control" %>
                </div>

                <div class="form-group" style="margin: 0 auto; max-width: 400px">
                    <%= f.label :photograph %> <br>
                        <%= f.file_field :photograph, :class => "form-control" %>
                </div>

                <div class="form-group" style="margin: 0 auto; max-width: 400px">
                    <%= f.label :caption %> <br>
                        <%= f.text_area :caption, :class => "form-control" %>
                </div>

                <label></label>
                <div class="button" style="text-align: center">
                    <fieldset class="actions">
                        <label></label>
                        <%= f.submit 'update me!', :class => "btn btn-info" %>
                    </fieldset>
                </div>

                <% end %>
                    <% end %>

app/views/posts/index.html.erb
<nav>
    <div class="profile-links">
        <% if @current_user.present? %>

            <div class="user-links">
                <%= link_to "other posts", posts_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to 'home', root_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            <% else %>
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                <% end %>
                    |
    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>

<h1>check out what other users have posted..</h1>

<div class="row">
  <% @posts.each do |post| %>
    <% next if post.user.id == @current_user.id %>

    <div class="col-xs-6 col-md-4">
        <div class="polaroid" style="width: 25vw; padding: 5px; margin: 0 auto">
            <% if post.photograph.nil? %>
            <p>
              <%= link_to post.title, post_path(post.id) %>
            </p>
                <%= link_to image_tag 'default-post.jpg', :class => "img-responsive" %>
              <% else %>              <p>
                <%= link_to post.title, post_path(post.id) %>
            </p>
                <%= link_to image_tag(post.photograph, :class => "img-responsive") %>
              <% end %>
            </div>
          </div>
        <% end %>
  </div>

app/views/posts/new.html.erb
<nav class="edit-nav">
    <div class="profile-links">

        <% if @current_user.present? %>
            <div class="user-links">
                <%= link_to 'home', root_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            |
            <% else %>
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                <% end %>

    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>


<h1>Make a new post</h1>

<% if @current_user %>

    <%= form_for @post, :html => {:multipart => true}, :class => "form-horizontal" do |f| %>
        <br>
        <div class="form-group" style="margin: 0 auto; max-width: 400px">
            <fieldset class="field">
                <%= f.label :title %><br>
                    <%= f.text_field :title, :class => "form-control" %>
            </fieldset>
        </div>
        <br>
        <div class="form-group" style="margin: 0 auto; max-width: 400px">
            <fieldset class="field">
                <%= f.label :photograph %><br>
                    <%= f.file_field :photograph, :class => "form-control" %>
            </fieldset>
        </div>
        <br>
        <div class="form-group" style="margin: 0 auto; max-width: 400px">
            <fieldset class="field">
                <%= f.label :caption %><br>
                    <%= f.text_field :caption, :class => "form-control" %>
            </fieldset>
        </div>

        <br>
        <label></label>
        <div class="button" style="text-align: center">
            <fieldset class="actions">
                <label></label>
                <%= f.submit 'Post me!', :class => "btn btn-info" %>
            </fieldset>
        </div>

        <% end %>
            <% end %>

app/views/posts/show.html.erb
<nav class="edit-nav">
    <div class="profile-links">

        <% if @current_user.present? %>
            <div class="user-links">
                <%= link_to 'home', root_path %>
            </div>
            |
            <div class="user-links">
                <%= link_to "profile", user_path(@current_user.id) %>
            </div>
            |
            <div class="user-links">
                <%= link_to "sign out #{ @current_user.name }", login_path, :method => 'delete' %>
            </div>
            |
            <% else %>
                <div class="user-links">
                    <%= link_to 'login', login_path %>
                </div>
                |
                <div class="user-links">
                    <%= link_to 'sign up', new_user_path %>
                </div>
                <% end %>

    </div>
    <%= image_tag "home/logo.png", :class => "logo" %>
</nav>

<h1>posts..</h1>

<div class="row-posts">

    <div class="col-md-6">
        <div class="polaroid">

              <% if @post.photograph.nil? %>
                  <%= image_tag 'default-post.jpg', :class => "img-responsive" %>
                  <p><%= @post.title %></p>
                <% else %>
                    <%= image_tag(@post.photograph, :class => "img-responsive") %>
                    <p><%= @post.title %></p>
                        <% end %>
        </div>
    </div>
<div>


<div class="row-comments">
  <div class="col-md-6">
  <br>
  <button class="glyphicon glyphicon-heart"></button>
  <button class="glyphicon glyphicon-cutlery"></button>
  <button class="glyphicon glyphicon-sunglasses"></button>

  <% if @current_user.present? %>
      <%= form_for [@post, @post.comments.new] do |f| %>
          <%= f.text_field :content, placeholder: 'add a comment...' %>
          <%= f.submit 'add comment', :class => "btn btn-danger" %>
      <% end %>
  <% else %>
    <%= link_to 'login', login_path %>
  <% end %>
  </div>
</div>


  <div class="row-comments">
      <div class="col-md-6">
          <%= @post.caption %>
          <hr>
          <% @post.comments.each do |comment| %>
          <p>
              <%#= comment.inspect %>
              <% next unless comment.persisted? # WTF IS GOING ON HERE %>
              <strong><%= comment.user.name %>:</strong>
              <%= comment.content %>
                      <br>
          </p>
          <% end %>
      </div>
    </div>
  </div>


<div>
    <% if @post.user_id == @current_user %>
        <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
</div>


<% if @post.user.id == @current_user.id %>
    <%= link_to 'edit', edit_post_path(@post.id) %>
        |
        <%= link_to 'delete', post_path(@post.id), :method => 'delete'  %>
            <% end %>